# This job listens for newly pushed tags. For each found tag, it will will
# do a static build, create a release, and upload said binary to the new
# release's assets.

name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build statically linked vmtest
      run: |
        ./scripts/build_release.sh

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        generate_release_notes: true
        files: ./vmtest-*
